# Generated by Django 3.2.4 on 2021-06-27 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210626_0348'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
