# Generated by Django 3.2.4 on 2021-06-27 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210627_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user_image',
            field=models.ImageField(default='default.jpg', upload_to='user_comment_pics'),
        ),
    ]
